// Code generated by tygo. DO NOT EDIT.
// AUTO-GENERATED — do not edit manually.
// Source: email_contracts Go package. Run `go tool tygo generate` in email_contracts/ to regenerate.

//////////
// source: connect_mps.go

/**
 * ConnectMPSData holds template variables for the ConnectMPS email.
 */
export interface ConnectMPSData {
  userName: string;
  userEmail: string;
  userOrganization: string;
  mpsNumber: string;
}

//////////
// source: connection_pending_approval.go

/**
 * ConnectionPendingApprovalData holds template variables for the ConnectionPendingApproval email.
 */
export interface ConnectionPendingApprovalData {
  contactName: string;
  contactEmail: string;
  contactPhone: string;
  contactOrganizationName: string;
  clientNumber: string;
  supplierName: string;
}

//////////
// source: deliveries_auto_confirmed.go

/**
 * DeliveryProduct is a single product line in a DeliveriesAutoConfirmedData email.
 */
export interface DeliveryProduct {
  name: string;
  amount: string;
  productCategory: string;
}
/**
 * DeliveriesAutoConfirmedData holds template variables for the DeliveriesAutoConfirmed email.
 * Note: the Products field requires a {{ range .Products }}...{{ end }} loop in the HTML template;
 * it cannot be auto-generated by toGoTemplate.
 */
export interface DeliveriesAutoConfirmedData {
  supplierName: string;
  date: string;
  stockLocation: string;
  appURL: string;
  products: DeliveryProduct[];
}

//////////
// source: forgot_password.go

/**
 * ForgotPasswordData holds template variables for the ForgotPassword email.
 */
export interface ForgotPasswordData {
  firstName: string;
  lastName: string;
  preposition: string;
  secret: string;
  appURL: string;
  s3Bucket: string;
  forgotPasswordURL: string;
}

//////////
// source: invoice_finalized.go

/**
 * InvoiceFinalizedData holds template variables for the InvoiceFinalized email:
 * the invoice of a customer we charge by direct debit. Stripe does not mail that
 * one itself — it only notifies the customer of the debit and, once the money has
 * settled, of the payment — so this mail is what puts the invoice in their inbox.
 * The PDF travels as an attachment, so the template only links the hosted page.
 */
export interface InvoiceFinalizedData {
  organizationName: string;
  invoiceNumber: string;
  /**
   * Amount due, formatted in the reader's language, with its currency symbol.
   */
  amount: string;
  hostedInvoiceURL: string;
}

//////////
// source: missing_distributor.go

/**
 * MissingDistributorData holds template variables for the MissingDistributor email.
 */
export interface MissingDistributorData {
  id: string;
  name: string;
  contact: string;
  country: string;
  phoneNumber: string;
  website: string;
  reportedBy: string;
}

//////////
// source: order_product.go

/**
 * OrderProductData holds template variables for the OrderProduct email.
 */
export interface OrderProductData {
  products: string;
  product: string;
  wCode: string;
  admissionCategory: string;
  customerOrganization: string;
  customerName: string;
  customerEmail: string;
  distributor: string;
}

//////////
// source: request_user_access.go

/**
 * RequestUserAccessData holds template variables for the RequestUserAccess email.
 */
export interface RequestUserAccessData {
  appURL: string;
  requester: string;
  receiver: string;
  organization: string;
}
