// Code generated by tygo. DO NOT EDIT.
// AUTO-GENERATED — do not edit manually.
// Source: email_contracts Go package. Run `go tool tygo generate` in email_contracts/ to regenerate.

//////////
// source: connect_mps.go

/**
 * ConnectMPSData holds template variables for the ConnectMPS email.
 */
export interface ConnectMPSData {
  userName: string;
  userEmail: string;
  userOrganization: string;
  mpsNumber: string;
}

//////////
// source: connection_pending_approval.go

/**
 * ConnectionPendingApprovalData holds template variables for the ConnectionPendingApproval email.
 */
export interface ConnectionPendingApprovalData {
  contactName: string;
  contactEmail: string;
  contactPhone: string;
  contactOrganizationName: string;
  clientNumber: string;
  supplierName: string;
}

//////////
// source: forgot_password.go

/**
 * ForgotPasswordData holds template variables for the ForgotPassword email.
 */
export interface ForgotPasswordData {
  firstName: string;
  lastName: string;
  preposition: string;
  secret: string;
  appURL: string;
  s3Bucket: string;
  forgotPasswordURL: string;
}

//////////
// source: missing_distributor.go

/**
 * MissingDistributorData holds template variables for the MissingDistributor email.
 */
export interface MissingDistributorData {
  id: string;
  name: string;
  contact: string;
  country: string;
  phoneNumber: string;
  website: string;
  reportedBy: string;
}

//////////
// source: order_product.go

/**
 * OrderProductData holds template variables for the OrderProduct email.
 */
export interface OrderProductData {
  products: string;
  product: string;
  wCode: string;
  admissionCategory: string;
  customerOrganization: string;
  customerName: string;
  customerEmail: string;
  distributor: string;
}

//////////
// source: request_user_access.go

/**
 * RequestUserAccessData holds template variables for the RequestUserAccess email.
 */
export interface RequestUserAccessData {
  appURL: string;
  requester: string;
  receiver: string;
  organization: string;
}
